name: CI -> Deploy to My website
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via FTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 'buezu09.ch'
          username: 'buezu09.ch'
          password: 'Buezu1909$'
          port: 21
          source: "."
          target: "/github.buezu09.ch//public_html/"
