name: CI -> Deploy to My website
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 'lx61.hoststar.hosting'
          username: 'buezu09.ch'
          password: 'Buezu1909$'
          server-dir: '/github.buezu09.ch/public_html/'
